create table ORDERS(
    ORDER_ID NUMBER(12,0) PRIMARY KEY,
    ORDER_DATE DATE,
    ORDER_MODE VARCHAR2(8 BYTE) CHECK (ORDER_MODE IN ('direct', 'online')),
    CUSTOM_ID NUMBER(6,0),
    ORDER_STATUS NUMBER(2,0),
    ORDER_TOTAL NUMBER(8,2) DEFAULT 0,
    SALES_REP_ID NUMBER(6,0 ),
    PROMOTION_ID NUMBER(6, 0)
);

create table ORDER_ITEMS(
    ORDER_ID NUMBER(12, 0),
    LINE_ITEM_ID NUMBER(3, 0),
    PORDUCT_ID NUMBER(3, 0),
    UNIT_PRICE NUMBER(8, 2) DEFAULT 0,
    QUANTITY NUMBER(8, 0) DEFAULT 0,
    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ID, LINE_ITEM_ID)
);

CREATE TABLE PROMOTIONS(
    PROMO_ID NUMBER(6, 0) PRIMARY KEY,
    PROMO_NAME VARCHAR2(20)
);

CREATE SEQUENCE ORDERS_SEQ
START WITH 1000
MAXVALUE 99999999
MINVALUE 1;