-- 1번 문제
select hire_year, count(*)
from (select to_char(hire_date, 'yyyy') hire_year
    from employees)
group by hire_year
order by 1;

-- 2번 문제
select PERIOD, REGION, SUM(LOAN_JAN_AMT) 
from kor_loan_status
GROUP BY GROUPING SETS (PERIOD, REGION);

-- 3번 문제
SELECT PERIOD, GUBUN, SUM(LOAN_JAN_AMT) TOTL_JAN
FROM KOR_LOAN_STATUS
WHERE PERIOD LIKE '2013%'
GROUP BY GROUPING SETS (PERIOD, (PERIOD, GUBUN), null);

-- 4번 문제
SELECT PERIOD,
    CASE WHEN GUBUN = '주택담보대출' THEN SUM(LOAN_JAN_AMT) ELSE 0 END 주택담보대출액,
    CASE WHEN GUBUN = '기타대출' THEN SUM(LOAN_JAN_AMT) ELSE 0 END 기타대출액
FROM KOR_LOAN_STATUS
WHERE PERIOD = '201311'
GROUP BY PERIOD, GUBUN;

-- 출력결과를 집합 연산자를 이용해서 동일한 결과를 출력하는 문제
SELECT PERIOD, 0 AS 주택담보대출액, SUM(LOAN_JAN_AMT) 기타대출액
FROM KOR_LOAN_STATUS
WHERE PERIOD = '201311' AND GUBUN = '주택담보대출'
GROUP BY PERIOD
UNION
SELECT PERIOD, SUM(LOAN_JAN_AMT) 주택담보대출액, 0 AS 기타대출액
FROM KOR_LOAN_STATUS
WHERE PERIOD = '201311' AND GUBUN = '주택담보대출'
GROUP BY PERIOD
ORDER BY 2 DESC;

-- 5번문제
SELECT REGION, PERIOD, SUM(LOAN_JAN_AMT)
FROM KOR_LOAN_STATUS
GROUP BY REGION, PERIOD;